// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcg9ck9PdbIw_5s0SLMlM2MQPjhwg59_E',
    appId: '1:812113344246:web:e740cfca7754fadb099ed7',
    messagingSenderId: '812113344246',
    projectId: 'todo-challenge-vtech',
    authDomain: 'todo-challenge-vtech.firebaseapp.com',
    storageBucket: 'todo-challenge-vtech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdc07w0RghP8fSsGbx2RDLgWtQNFDypjU',
    appId: '1:812113344246:android:fd1ea6443458cebe099ed7',
    messagingSenderId: '812113344246',
    projectId: 'todo-challenge-vtech',
    storageBucket: 'todo-challenge-vtech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4B6S3lm6eHpBaXqcDc6rFr6zZtHpqKw',
    appId: '1:812113344246:ios:1d5ed8f5148aed59099ed7',
    messagingSenderId: '812113344246',
    projectId: 'todo-challenge-vtech',
    storageBucket: 'todo-challenge-vtech.firebasestorage.app',
    iosBundleId: 'com.example.todoChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4B6S3lm6eHpBaXqcDc6rFr6zZtHpqKw',
    appId: '1:812113344246:ios:1d5ed8f5148aed59099ed7',
    messagingSenderId: '812113344246',
    projectId: 'todo-challenge-vtech',
    storageBucket: 'todo-challenge-vtech.firebasestorage.app',
    iosBundleId: 'com.example.todoChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcg9ck9PdbIw_5s0SLMlM2MQPjhwg59_E',
    appId: '1:812113344246:web:108486e23c686b23099ed7',
    messagingSenderId: '812113344246',
    projectId: 'todo-challenge-vtech',
    authDomain: 'todo-challenge-vtech.firebaseapp.com',
    storageBucket: 'todo-challenge-vtech.firebasestorage.app',
  );
}
